spring:
  application:
    name: asdf
  threads:
    virtual:
      enabled: true
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  shell:
    interactive:
      enabled: true

server:
  port: 0
