name: 배포자동화
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 최근 커밋 해시 가져오기
        id: last_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%H)"
        shell: bash

      - name: 현재 브랜치 이름 가져오기
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${{ github.ref }} | awk -F/ '{print $3}')"
        shell: bash

      - name: Ensure cache directory exists
        run: mkdir -p ~/.gradle/caches
        shell: bash

      - name: 캐시에서 값 가져오기
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ steps.branch_name.outputs.branch }}-${{ steps.last_commit.outputs.message }}


      - name: Set up JDK 17
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'coretto'

      - name: test
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
            chmod +x ./gradlew
            ./gradlew clean test -parallel

      - name: Save cache
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ steps.branch_name.outputs.branch }}-${{ steps.last_commit.outputs.message }}

      - name: kkk
        if: steps.cache-restore.outputs.cache-hit == 'true'
        run : echo '캐시 적중~!'

